# Generated by Django 3.2.4 on 2022-03-12 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noteapp', '0002_rename_user_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(max_length=1000)),
                ('intrest', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('1', 'Normal_user'), ('2', 'Employee'), ('3', 'Admin')], default='1', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
